### ISSUE TITLE
Clarification about the SetTextInput example in form-inputs.md.

### ISSUE THREAD

**Issue by Wallace-Kelly** [Zaid-Ajaj/the-elmish-book#139]
Are you accepting questions here as GitHub issues?

The following text appears in [the-elmish-book\chapters\elm\form-inputs.md](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/form-inputs). It is in the context of a code sample which copies input text from an input element to an adjacent span element.

> We should mention here that even when the UI is re-rendered, the input box element preserves the text that has been entered. We didn't tell the input element that it should use state.TextInput but still with each render cycle, the text is kept as it is. This makes sense because if it did reset the internal state with every cycle, then the text box would be cleared after each keyboard stroke which is not exactly what your users would be expecting.  
>  
> This happens because HTML input elements such as a text box keep track of an internal state of their own so we don't have to tell the input box what text it should have now. 

I am trying to understand this more clearly. The `render` function is called after every call to the `update` function, correct? Surely the generated JavaScript is not instantiating new HTML elements after every call to the `update` function. Or does it? I would have expected that some kind of React binding mechanism is being used under-the-hood. However, that seems inconsistent with calling the `render` function after every `update`. Instead, is there some kind of diff going on between the previous rendering and the next rendering that "manually" updates the elements based on changes? If "conditional rendering" inside the `render` function were to place the input box at a different place in the HTML hierarchy, would that result in a new text box instance? and a resulting loss of the previous text box's internal state?

**Comment by Zaid-Ajaj** [comment]
Hi there @Wallace-Kelly, 

Yes, GitHub issues are just fine for questions, as well as the [F# slack](https://fsharp.org/guides/slack) where F# people hang out and can answer all questions you have :smile: 

> The render function is called after every call to the update function, correct?

Yes

> Surely the generated JavaScript is not instantiating new HTML elements after every call to the update function. Or does it? 

The generated JavaScript does *not* instantiate new HTML elements, it returns the newly generated *virtual DOM* tree back to React where React will decide whether elements should be completely removed then re-instantiated or they should be only mutated. 

> I would have expected that some kind of React binding mechanism is being used under-the-hood. However, that seems inconsistent with calling the render function after every update.

It is indeed consistent: the `render` function works *with* React and not with the DOM directly. The fact that it runs after each update is necessary to tell React that the user interface should be invalidated based on the newly returned virtual DOM tree. 

> Instead, is there some kind of diff going on between the previous rendering and the next rendering that "manually" updates the elements based on changes? 

Yes, this is exactly what React does. See [React in Elmish](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/react-in-elmish) section.

>  If "conditional rendering" inside the render function were to place the input box at a different place in the HTML hierarchy, would that result in a new text box instance? and a resulting loss of the previous text box's internal state?

Yes that would indeed result in a new instance of the text box, however since we are using `prop.valueOrDefault` it will overwrite the internal state of the text box once it is re-initialized and it will stay in sync with the state of the Elmish program. (Please try it out to see for yourself) 

I hope this made it clear for you, if not please let me know!

**Comment by Wallace-Kelly** [comment]
Yes, that is very helpful. Thank you for the quick response.

**Comment by Zaid-Ajaj** [comment]
Anytime :wink:

**Comment by Wallace-Kelly** [comment]
Ha! As you said, I just needed to turn the page.

> In the previous sections, we talked quite a bit about the `render` function. This function takes the current state of the application and creates the user interface from it. *Every* time the state changes, the `render` function is invoked and the user interface is updated accordingly.

> At this point, the `render` function has probably piqued your interest but you have put it in the back of your mind as some "black box" doing the magic. In this section, we will try to remedy the situation and understand how Elmish updates the user interface and how it does so in a performant manner.
